print("Welcome to the Band Name Generator.")
a = input("What's name of the city you grew up in?")
print(a)
b = input("What's your pet's name?")
print(b)
print("Your band name could be " + a + " " + b)